import Head from 'next/head'
import ImageHolder from '../components/ImageHolder'
import Link from 'next/link'
import PictureTab from '../components/PictureTab'
import ButtonMaker from '../components/ButtonMaker'
import HomeSlider from '../components/HomeSlider'
import { arrows } from '../components/HomeSliderPages'
import { useEffect } from 'react'
import slides from '../components/HomeSliderPages'

export default function Home({ bgSwitcher, homeSlidePage, setHomeSlidePage, isContactForm, setIsContactForm, openForm }) {


useEffect(() => {
    let setPics = setInterval(() => {
      if(Number(slides[homeSlidePage].page) == slides.length){
        setHomeSlidePage(0)
        return
      }       
      setHomeSlidePage(homeSlidePage+1)
    }, 10000)

    return (() => {
        clearInterval(setPics)
    })
}, [homeSlidePage])


  return (
    <div className={`relative mt-[-400px] ${isContactForm ? "blur-lg" : "blur-none"} md:mt-[-645px] lg:mt-[-850px] xl:mt-[-900px] h-fit overflow-none`}>
      <Head>
        <title>Japtini Logistics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col relative h-[400px] md:h-[600px] lg:h-[850px] xl:h-[900px] bg-none">
        <div className='absolute z-[80] left-[50%] bottom-[-25px]'>
          <div className='hidden relative md:block w-[64px] h-[64px]'>
            <ImageHolder src="/page-marker.png" />
          </div>
        </div>
        <div className='flex flex-col mt-[100px] lg:mt-[250px] w-fit ml-[20px] md:ml-[112px]'>
          <section className='flex items-center w-[150px] md:w-[350px] justify-around'>
            <div className='relative w-[20px] h-[20px] md:w-[48px] md:h-[48px]'>
              <ImageHolder src="/listen.png" />
            </div>
            <h2 className='font-konreg font-[700] text-[white] text-[30px] md:text-[72px]'>Japtini</h2>
          </section>
          <section className='flex flex-col'>
            <h2 className='text-[white] font-raleway text-[15px] md:text-[20px]'>Ogbia language of Central Delta, Nigeria</h2>
            <h2 className='text-[white] font-[700] font-raleway text-[25px]'>
              Denotes stewardship, care <br></br>
              ”We take responsibility for what is ours”
            </h2>

          </section>
        </div>


        <div className='md:flex hidden md:flex items-center xl:items-start md:pl-[112px] md:pr-[50px] lg:mt-[112px] justify-around md:justify-between lg:grow'>
          {[
            {
              blur: "/haulage-blur.png",
              clear: "/haulage-clear.png",
              large: "/haulage-large.png",
              text: "Haulage",
              url: "/services/haulage"

            },
            {
              blur: "/goods-blur.png",
              clear: "/goods-clear.png",
              large: "/goods-large.png",
              text: "Goods Producers",
              url: "/services/goods-producers"

            },
            {
              blur: "/transport-blur.png",
              clear: "/transport-clear.png",
              large: "/transport-large.png",
              text: "Transport",
              url: "/services/transport-services"

            },
            {
              blur: "/warehouse-blur.png",
              clear: "/warehouse-clear.png",
              large: "/warehouse-large.png",
              text: "Warehousing",
              url: "/services/warehousing-and-distribution"

            }
          ].map((item, index) => {
            return <PictureTab key={index} url={item.url} nodeKey={index} onHover={bgSwitcher} src={item.large} blur={item.blur} clear={item.clear} text={item.text} />
          })}
        </div>
      </div>


      <div className='flex h-[fit] md:h-fit flex-col lg:flex-row relative lg:h-[800px] w-full'>
        <section className='lg:w-[60%] min-h-[600px] flex flex-col items-center lg:h-full bg-[#231F20]'>
          <h2 className='font-konregular lg:w-[95%] xl:w-[80%] text-center md:text-start text-[white] font-[700] text-[72px]'>
            Can a truck
            <br></br>
            <span className='text-[#F7941D] cursor-pointer'> tame inflation?</span>
          </h2>
          <section className='flex lg:w-[95%] pb-[10px] xl:justify-between xl:w-[80%] mt-[27px] w-full min-h-[425px]'>
            <div className='hidden lg:flex bg-[#F7941D] rounded-[12px] w-[8px] h-full'></div>
            <div className='flex h-fit text-center lg:text-start md:break-words flex-col md:ml-[10px] lg:w-[95%] xl:w-[663px]'>
              <p className='break-words font-intregular lg:w-[100%] xl:font-[500] xl:text-[16px] text-[#E8E8E8]'>

                In a word, <span className='font-[600] cursor-pointer text-[#F7941D]'>Logistics.</span>
                <br></br>
                <br></br>

                It isn’t only food that gets stuck: medicines, toiletries, clothing - all manner of
                essential goods.
                <br></br>
                <br></br>

                The transport challenge is why logistics make up 40% of the overall cost
                of goods in Africa. In the US, the logistics cost is around 6%.
                Some of the
                causes are beyond our control: bad roads, security threats, weather
                events.
                But other factors, we can address, such as shortages of trucks
                and suitable warehousing, cargo thefts, and transport reliability.
                <br></br>
                <br></br>
                Using smart logistics mapping, verification systems and tracking,
                <br></br>
                <span className='font-[600] text-[#F7941D] cursor-pointer'>
                  Japtini Logistics is bringing down the cost of haulage and storage
                  across the continent.
                </span>
              </p>

              <div className='md:block h-[62px] border border-black w-[145px] mt-[20px] m-auto lg:m-0 w-fit lg:mt-[32px]'>
                <ButtonMaker text="Get on Board" command={openForm} />
              </div>
              
            </div>
          </section>
        </section>
        <section style={{ backgroundImage: `url(/woman-homepage.png)` }} className='hidden lg:flex relative bg-center bg-cover h-full lg:w-[40%]'></section>
      </div>
      <section className='flex h-[650px] md:mt-0 relative w-full items-center bg-gradient-to-r from-[#F7F7F7] to-[#D4D4D4]'>
        <HomeSlider homeSlidePage={homeSlidePage} setHomeSlidePage={setHomeSlidePage} page="home" />
      </section>

         </div>
  )
}
